### ISSUE TITLE
I can not run python example_contourApproach.py

### ISSUE THREAD

**Issue by wyg110sjtu** [WEC-Sim/WDRT#18]
Dear WDRT developers: 
      This is John again. I ran WDRT :
cd examples
python example_envSamplying.py
      I could only get a PCA contour line. NO contour lines via other methods could be obtained. 
Meanwhile when I continued to run "python example_contourApproach.py", I got the following warnings:
  "Traceback (most recent call last):
  File "C:\WDRT\WDRT-master\examples\example_contourApproach.py", line 15, in <module>
    Hs = np.array(envFile['buoy_Data/Hs'])
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (C:\aroot\work\h5py\_objects.c:2463)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (C:\aroot\work\h5py\_objects.c:2420)
  File "C:\Users\wyg\Anaconda\lib\site-packages\h5py\_hl\group.py", line 164, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (C:\aroot\work\h5py\_objects.c:2463)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (C:\aroot\work\h5py\_objects.c:2420)
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open (C:\aroot\work\h5py\h5o.c:3373)
KeyError: 'Unable to open object (Component not found)'

Why?

Please kindly reply me.

Yours,

John Wang

**Comment by aubreyeckert** [comment]
Hello John @wyg110sjtu ,

Thank you for alerting us to this issue. I believe that the example file that you are running is outdated and needs to be updated to reflect recent code changes. We will let you know when this updated example is available. In the meantime, the documentation for each contour method should provide working examples that will allow you to run all methods. 

Thank you,
Aubrey

**Comment by wyg110sjtu** [comment]
Many thanks, Aubrey.

Yours,

John

**Comment by rgcoe** [comment]
@wyg110sjtu - Thank you for identifying this bug. We have fixed this w/ f9e2c4706a919f832da1e5496fe723cb5722c541.
