### ISSUE TITLE
Data type mismatch from CDIP buoy

### ISSUE THREAD

**Issue by Toby-D** [WEC-Sim/WDRT#8]
It looks like there's a float vs. double mismatch when calculating the nonparametric Copulas from CDIP data. (Here I simply changed example_envSampling.py to call CDIP buoy # 160 and uncommented all the contour methods. 

```
$ python example_envSampling.py
Downloading data from: http://thredds.cdip.ucsd.edu/thredds/fileServer/cdip/archive/160p1/160p1_historic.nc
Traceback (most recent call last):
  File "example_envSampling.py", line 39, in <module>
    NonParaGauss46022 = ESSC.NonParaGaussianCopula(buoy46022)
  File "build\bdist.win-amd64\egg\WDRT\ESSC.py", line 1650, in __init__
  File "build\bdist.win-amd64\egg\WDRT\ESSC.py", line 462, in __getNonParaCopulaParams
  File "C:\Users\Toby\Anaconda\lib\site-packages\statsmodels\nonparametric\kde.py", line 146, in fit
    clip=clip, cut=cut)
  File "C:\Users\Toby\Anaconda\lib\site-packages\statsmodels\nonparametric\kde.py", line 494, in kdensityfft
    binned = fast_linbin(X,a,b,gridsize)/(delta*nobs)
  File "statsmodels/nonparametric/linbin.pyx", line 17, in statsmodels.nonparametric.linbin.fast_linbin (statsmodels/nonparametric/linbin.c:1343)
ValueError: Buffer dtype mismatch, expected 'DOUBLE' but got 'float'
```

**Comment by tyleresterly** [comment]
The problem seems to be that, even though the values from that CDIP buoy were being stored and loaded in as doubles, scipy wasn't recognizing them as such without being explicitly labeled doubles... In any case, the problem should be fixed in the latest commit.

**Comment by Toby-D** [comment]
Thanks Tyler!

(And good call making loadCDIP public, so it's easier to avoid downloading the .nc file every time.)
